<?xml version="1.0" encoding="UTF-8" ?>
<testsuite name="tst_DataTable" tests="10" failures="13" errors="0">
  <properties>
    <property name="QTestVersion" value="@INSERT_QT_VERSION_HERE@"/>
    <property name="QtVersion" value="@INSERT_QT_VERSION_HERE@"/>
    <property name="QtBuild" value=""/>
  </properties>
  <testcase name="initTestCase" result="pass"/>
  <testcase name="singleTestFunction1" result="pass"/>
  <testcase name="singleTestFunction2" result="pass"/>
  <testcase name="fiveTablePasses" result="pass"/>
  <testcase name="fiveTableFailures" result="fail">
    <failure result="fail" message="&apos;test&apos; returned FALSE. ()" tag="fiveTableFailures_data 1"/>
    <failure result="fail" message="&apos;test&apos; returned FALSE. ()" tag="fiveTableFailures_data 2"/>
    <failure result="fail" message="&apos;test&apos; returned FALSE. ()" tag="fiveTableFailures_data 3"/>
    <failure result="fail" message="&apos;test&apos; returned FALSE. ()" tag="fiveTableFailures_data 4"/>
    <failure result="fail" message="&apos;test&apos; returned FALSE. ()" tag="fiveTableFailures_data 5"/>
  </testcase>
  <testcase name="startsWithFailure" result="fail">
    <failure result="fail" message="&apos;test&apos; returned FALSE. ()" tag="startsWithFailure_data 1"/>
  </testcase>
  <testcase name="endsWithFailure" result="fail">
    <failure result="fail" message="&apos;test&apos; returned FALSE. ()" tag="endsWithFailure 5"/>
  </testcase>
  <testcase name="failureInMiddle" result="fail">
    <failure result="fail" message="&apos;test&apos; returned FALSE. ()" tag="failureInMiddle_data 3"/>
  </testcase>
  <testcase name="fiveIsolatedFailures" result="fail">
    <failure result="fail" message="&apos;!test&apos; returned FALSE. ()" tag="fiveIsolatedFailures_data 1"/>
    <failure result="fail" message="&apos;!test&apos; returned FALSE. ()" tag="fiveIsolatedFailures_data 2"/>
    <failure result="fail" message="&apos;!test&apos; returned FALSE. ()" tag="fiveIsolatedFailures_data 3"/>
    <failure result="fail" message="&apos;!test&apos; returned FALSE. ()" tag="fiveIsolatedFailures_data 4"/>
    <failure result="fail" message="&apos;!test&apos; returned FALSE. ()" tag="fiveIsolatedFailures_data 5"/>
  </testcase>
  <testcase name="cleanupTestCase" result="pass"/>
  <system-err/>
</testsuite>
